
 # JWT configuration
jwt:
  header: Authorization
  secret: mySecret
  expiration: 60 #单位：分钟
  tokenHead: Bearer


client:
  id: sale-oranges
  secret: geng
  token-header: client-token
  expire: 60
  rsa-secret: (๑•̀ㅂ•́)و✧