spring:
  application:
    name: admin-users
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/common_admin_users?useUnicode=true&characterEncoding=utf8
    username: geng
    password: 123
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: blog
  thymeleaf:
    enabled: false #不需要html模板

#  jpa:
#    show-sql: true

server:
  port: 8080

eureka:
  instance:
    statusPageUrlPath: /entity
    healthCheckUrlPath: /health
    homePageUrl: http://${eureka_host:localhost}:${server.port}/
  client:
    serviceUrl:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/

# 配置参考 https://github.com/Netflix/Hystrix/wiki/Configuration
# https://blog.csdn.net/harris135/article/details/77879148?locationNum=3&fps=1
hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

client:
  id: admin-users
  secret: geng
  token-header: client-token
  expire: 60
  rsa-secret: (\^-^\)
