spring:
  application:
    name: admin-users
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/common_admin_users?useUnicode=true&characterEncoding=utf8
    username: geng
    password: 123
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: blog
  thymeleaf:
    enabled: false #不需要html模板

  jpa:
    show-sql: true

server:
  port: 8080

 #看情况整合redis
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug